[package]
name = "serde_inner_serialize_derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
serde_inner_serialize_core = { path = "../serde_inner_serialize_core" }
proc-macro-error = "1.0"
proc-macro2 = "1.0"